import sys
from pathlib import Path
import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.copilot.engine import CampaignCopilot
from src.copilot.models import CopilotRequest
from src.copilot.provider import LocalLLMProvider
from src.data.loader import load_campaigns, load_contacts

st.set_page_config(page_title="CampaignOS | Campaign Copilot", page_icon="🧠", layout="wide")
st.title("🧠 Local LLM Campaign Copilot")
st.caption("Generate campaign briefs, audience strategy, optimization guidance and marketing copy using a local LLM or the deterministic CampaignOS fallback.")

campaigns = load_campaigns()
contacts = load_contacts()
if campaigns.empty or contacts.empty:
    st.error("Campaign or contact synthetic data is unavailable.")
    st.stop()

st.sidebar.header("Copilot Configuration")
selected_campaign = st.sidebar.selectbox("Campaign", campaigns["campaign_name"].astype(str).tolist())
campaign = campaigns[campaigns["campaign_name"].astype(str) == selected_campaign].iloc[0]
task = st.sidebar.selectbox("Copilot Task", ["Campaign Brief", "Audience Strategy", "Optimization Recommendations", "Email Copy"])
tone = st.sidebar.selectbox("Tone", ["Professional", "Executive", "Consultative", "Concise"])
region = st.sidebar.selectbox("Region", ["Campaign Region", "WW", "APAC", "AMEA", "Europe"])
region_value = str(campaign["region"]) if region == "Campaign Region" else region

campaign_contacts = contacts[contacts["region"].astype(str) == region_value].copy()
avg_score = float(campaign_contacts["lead_score"].mean()) if not campaign_contacts.empty else 0.0
mql_count = int((campaign_contacts["lifecycle_stage"] == "MQL").sum()) if not campaign_contacts.empty else 0
marketable_count = int((campaign_contacts["consent_status"].astype(str) == "Opted In").sum()) if not campaign_contacts.empty else 0
audience = f"{region_value} contacts; {len(campaign_contacts):,} synthetic contacts; {mql_count:,} MQLs; {marketable_count:,} opted-in contacts"
context = {"Campaign status": str(campaign["status"]), "Campaign budget": str(campaign["budget"]), "Campaign objective": str(campaign["objective"]), "Average contact lead score": round(avg_score, 1), "MQL count": mql_count, "Marketable contacts": marketable_count}

k1, k2, k3, k4 = st.columns(4)
k1.metric("Campaign", selected_campaign)
k2.metric("Region", region_value)
k3.metric("Audience", f"{len(campaign_contacts):,}")
k4.metric("Avg Lead Score", f"{avg_score:.1f}")

st.subheader("Campaign Context")
context_df = pd.DataFrame([{"Field": k, "Value": v} for k, v in context.items()])
context_df["Value"] = context_df["Value"].astype(str)
st.dataframe(context_df, width="stretch", hide_index=True)

st.subheader("Copilot Execution")
provider = LocalLLMProvider()
health = provider.health()
status_col, model_col = st.columns(2)
with status_col:
    if health:
        st.success("Local LLM available")
    else:
        st.info(
            "Local LLM unavailable. CampaignOS will use its deterministic fallback engine."
        )

with model_col:
    st.write(f"**Configured model:** `{provider.model}`")
st.write("No cloud API key is required. If Ollama is running locally, CampaignOS uses it; otherwise the same workflow remains demonstrable through the deterministic fallback.")

if st.button("✨ Generate Copilot Output", type="primary"):
    request = CopilotRequest(task=task, campaign_name=selected_campaign, business_type=str(campaign["business_type"]), region=region_value, objective=str(campaign["objective"]), audience=audience, tone=tone, context=context)
    with st.spinner("Generating campaign guidance..."):
        response = CampaignCopilot(provider=provider).run(request)
    st.warning("Output generated by the CampaignOS deterministic fallback. Start Ollama locally to switch to the LLM provider.") if response.used_fallback else st.success(f"Generated with local model `{response.model}`.")
    st.subheader("Copilot Output")
    st.markdown(response.content)
    m1, m2, m3 = st.columns(3)
    m1.metric("Provider", response.provider)
    m2.metric("Model", response.model)
    m3.metric("Fallback", "Yes" if response.used_fallback else "No")
    st.download_button("⬇️ Export Copilot Output", data=response.content.encode("utf-8"), file_name="campaignos_copilot_output.md", mime="text/markdown")

st.subheader("M9 Architecture")
st.markdown("""```text
Campaign Data
     ↓
CampaignOS Context Builder
     ↓
Copilot Request
     ↓
Local LLM Provider
     │
     ├── Ollama available → local model response
     │
     └── Ollama unavailable → deterministic fallback
     ↓
Validated Copilot Response
     ↓
Streamlit UI / Markdown Export
```

**Provider boundary:** no direct dependency on a cloud model vendor.

**Privacy boundary:** this module sends only synthetic CampaignOS context to a local Ollama endpoint.

**Operational boundary:** generated text is advisory. CampaignOS does not automatically send emails, modify CRM records, or execute external actions.""")

st.subheader("Suggested Local Setup")
st.code("ollama pull llama3.2:3b\nollama serve\nstreamlit run app/Home.py", language="bash")
